app = 'no-as-a-service'
primary_region = 'sin'
swap_size_mb = 512

[build]

[http_service]
force_https = true
internal_port = 3000
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'
memory = '512MB'
